autodetect: yes
strictness: medium
test-warnings: false
doc-warnings: true

ignore-paths:
  - .git
  - docs

pep8:
  run: true
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 120

